# Generated by Django 3.2.7 on 2021-09-19 19:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Logo', models.ImageField(upload_to='uploads/')),
                ('Favicon', models.ImageField(upload_to='uploads/')),
                ('Color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('MobileNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('FullName', models.CharField(max_length=200)),
                ('IsVerified', models.BooleanField()),
                ('Otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('MobileNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('FullName', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('ProfilePic', models.ImageField(upload_to='uploads/')),
                ('IsVerified', models.BooleanField()),
                ('IsActive', models.BooleanField()),
                ('Otp', models.IntegerField()),
            ],
        ),
    ]
