# Generated by Django 3.2.7 on 2021-09-20 20:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='MobileNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='IsVerified',
            field=models.BooleanField(default=False),
        ),
    ]
